name: Build Re:VIEW to make distribution file
# The workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    steps:
    # uses v2 Stable version
    # https://github.com/actions/checkout
    - name: checkout source
      uses: actions/checkout@v2
    # Build Artifacts
    - name: Build distribution file
      uses: TechBooster/ReVIEW-build-artifact-action@master
    - name: Get output values
      id: output
      run: |
        echo "::set-output name=date::$(date +"%Y%m%d")"
        echo "::set-output name=repo-name::${GITHUB_REPOSITORY##*/}"
        echo "::set-output name=commit-hash::${GITHUB_SHA:0:7}"
    # Upload Distribution file
    - name: Upload distribution file to github artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.output.outputs.repo-name }}-${{ steps.output.outputs.date }}-${{ steps.output.outputs.commit-hash }}
        path: ./articles/*.pdf
