name: Check Textlint
on:
  push:
    paths:
      - '**.re'
      - '.github/workflows/textlint.yml'
      - 'textlint/**'

jobs:
  build:
    name: Textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn --cwd textlint install --ignore-scripts
      - name: Check Textlint (with auto-fix)
        run: yarn --cwd textlint lint --fix
      - name: Check Textlint
        run: yarn --cwd textlint lint
      - name: Push auto-fixed files
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "👕 Fixed auto-fixable Textlint errors by github-actions"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}